services:
  web:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local