services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DEBUG: 1
    volumes:
      - ./:/app/backend
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:?err}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?err}
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  frontend:
    image: node:18-alpine
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - staticbuild:/frontend/out
      - ./:/app/frontend
volumes:
  db:
    driver: local
  staticbuild:
  pgadmin-data: