services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  frontend:
    image: node:18-alpine
    build: ./frontend
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - staticbuild:/frontend/out
volumes:
  db:
    driver: local
  staticbuild: